find_path(MONGOC_INCLUDE_DIR NAMES mongoc.h PATHS ${CONAN_INCLUDE_DIRS_MONGO-C-DRIVER})

set(MONGOC_FOUND TRUE)
set(MONGOC_STATIC_INCLUDE_DIRS ${MONGOC_INCLUDE_DIR})
set(MONGOC_STATIC_LIBRARIES ${CONAN_LIBS})
mark_as_advanced(MONGOC_LIBRARY MONGOC_INCLUDE_DIR)
