find_path(BSON_INCLUDE_DIR NAMES bson.h PATHS ${CONAN_INCLUDE_DIRS_MONGO-C-DRIVER})
find_library(BSON_LIBRARY NAMES ${CONAN_LIBS_MONGO-C-DRIVER} PATHS ${CONAN_LIB_DIRS_MONGO-C-DRIVER})

set(BSON_FOUND TRUE)
set(BSON_INCLUDE_DIRS ${BSON_INCLUDE_DIR})
set(BSON_STATIC_LIBRARIES bson)
mark_as_advanced(BSON_LIBRARY BSON_INCLUDE_DIR)
